add_newline = true

format = """$all$time$jobs[linux](bold yellow)🐧$character"""

[conda]
# symbol = "⭕"
symbol = "🅒 "

[jobs]
symbol = "⚙️ "
threshold = 1

[time]
disabled = false
format = '[⏱️ #$time]($style) '
time_format = "%T"
utc_time_offset = "+8"
